package com.liu.LeetCode.First.exercise;

/**
 * Created by liu on 2017/9/30.
 */
public class LC389_FindTheDifference {
    /**
     * Given two strings s and t which consist of only lowercase letters.
     * <p>
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * <p>
     * Find the letter that was added in t.
     * <p>
     * Example:
     * <p>
     * Input:
     * s = "abcd"
     * t = "abcde"
     * <p>
     * Output:
     * e
     * <p>
     * Explanation:
     * 'e' is the letter that was added.
     */

    public static char getFindTheDifferenceMy1(String s, String t) {
        int[] cache = new int[26];
        for (int i = 0; i < s.length(); i++) {
            cache[s.charAt(i) - 'a']++;
        }
        for (int i = 0; i < t.length(); i++) {
            cache[t.charAt(i) - 'a']--;
        }
        for (int i = 0; i < 26; i++) {
            if (cache[i] < 0) {
                return (char) ('a' + i);
            }
        }
        return t.charAt(t.length() - 1);
    }
}
